// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:356246633532:web:5aba54efed9a6e64c0d739',
    messagingSenderId: '356246633532',
    projectId: 'college-utility-app-se',
    authDomain: 'college-utility-app-se.firebaseapp.com',
    storageBucket: 'college-utility-app-se.firebasestorage.app',
    measurementId: 'G-VWZR19KJJ8',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
    appId: '1:356246633532:android:280e4b3ef54eb66cc0d739',
    messagingSenderId: '356246633532',
    projectId: 'college-utility-app-se',
    storageBucket: 'college-utility-app-se.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:356246633532:ios:4560b76bf43ef173c0d739',
    messagingSenderId: '356246633532',
    projectId: 'college-utility-app-se',
    storageBucket: 'college-utility-app-se.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_MACOS'] ?? '',
    appId: '1:356246633532:ios:4560b76bf43ef173c0d739',
    messagingSenderId: '356246633532',
    projectId: 'college-utility-app-se',
    storageBucket: 'college-utility-app-se.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WINDOWS'] ?? '',
    appId: '1:356246633532:web:6940cac7823ae5fdc0d739',
    messagingSenderId: '356246633532',
    projectId: 'college-utility-app-se',
    authDomain: 'college-utility-app-se.firebaseapp.com',
    storageBucket: 'college-utility-app-se.firebasestorage.app',
    measurementId: 'G-FK722GWGGV',
  );
}