import 'package:flutter/material.dart';
// import 'package:flutter_dotenv/flutter_dotenv.dart'; // Your custom env loader
import 'package:firebase_core/firebase_core.dart';   // Firebase Core
import 'package:firebase_auth/firebase_auth.dart';   // Firebase Auth
import 'firebase_options.dart';                      // Generated by FlutterFire
import 'auth_screen.dart';                           // The UI file we made

Future<void> main() async {
  // 1. Required to run async code before the app actually starts
  WidgetsFlutterBinding.ensureInitialized(); 

  // 2. Load your environment variables FIRST (from your original code)
  
  // 3. Initialize your Firebase project
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  // 4. Run the app
  runApp(const CampusUtilityApp());
}

class CampusUtilityApp extends StatelessWidget {
  const CampusUtilityApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Campus App',
      // Kept your original purple theme!
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple), 
      ),
      // StreamBuilder acts as the traffic cop for logged-in vs logged-out users
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          // Show a loading spinner while checking the connection
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }
          
          // If the snapshot has data, the user is logged in!
          if (snapshot.hasData) {
            return const DashboardScreen(); 
          }
          
          // If no data, they are logged out. Show the login screen.
          return const AuthScreen();
        },
      ),
    );
  }
}

// A temporary placeholder screen to prove the login worked
class DashboardScreen extends StatelessWidget {
  const DashboardScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Ride-Sharing & Lost-and-Found'),
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        actions: [
          // A handy logout button to test the flow
          IconButton(
            icon: const Icon(Icons.logout),
            onPressed: () => FirebaseAuth.instance.signOut(),
          ),
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              'Welcome! You are officially logged in.', 
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)
            ),
            const SizedBox(height: 16),
            const Text('Your Firebase UID is:'),
            Text(
              FirebaseAuth.instance.currentUser?.uid ?? 'Unknown', 
              style: const TextStyle(color: Colors.grey)
            ),
          ],
        ),
      ),
    );
  }
}